export const GET_PARK_LIST_REQUEST = "GET_PARK_LIST_REQUEST";
export const GET_PARK_LIST_SUCCESS = "GET_PARK_LIST_SUCCESS";
export const GET_PARK_LIST_FAIL = "GET_PARK_LIST_FAIL"

export const GET_PARK_DETAILS_REQUEST = "GET_PARK_DETAILS_REQUEST"
export const GET_PARK_DETAILS_SUCCESS = "GET_PARK_DETAILS_SUCCESS"
export const GET_PARK_DETAILS_FAIL = "GET_PARK_DETAILS_FAIL"